-- CREATION OF THE DATABASE PAYMYBUDDY
CREATE DATABASE IF NOT EXISTS prod;
USE prod;

-- CREATION OF THE 4 TABLES OF THE DATAMODEL FOR THE PAYMYBUDDY DATABASE
CREATE TABLE IF NOT EXISTS CLIENT (
                                      CLIENT_ID INT PRIMARY KEY AUTO_INCREMENT,
                                      FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS TRANSACTIONS(
                                           TRANSACTION_ID INT PRIMARY KEY AUTO_INCREMENT,
                                           SENDER_ID INT NOT NULL,
                                           BENEFICIARY_ID INT NOT NULL,
                                           AMOUNT DECIMAL(10,2) NOT NULL,
    DESCRIPTION VARCHAR(255),
    DATE DATETIME NOT NULL,
    STATUS INT NOT NULL,
    FOREIGN KEY (SENDER_ID) REFERENCES CLIENT(CLIENT_ID),
    FOREIGN KEY (BENEFICIARY_ID) REFERENCES CLIENT(CLIENT_ID)
    );

CREATE TABLE IF NOT EXISTS ACCOUNTS(
                                       ACCOUNT_ID INT PRIMARY KEY AUTO_INCREMENT,
                                       CLIENT_ID INT NOT NULL,
                                       BALANCE DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID)
    );

CREATE TABLE IF NOT EXISTS BENEFICIARIES
(
    BENEFICIARY_ID        INT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID             INT NOT NULL,
    BENEFICIARY_FIRSTNAME VARCHAR(255) NOT NULL,
    BENEFICIARY_LASTNAME VARCHAR(255) NOT NULL,
    FOREIGN KEY (BENEFICIARY_ID) REFERENCES CLIENT (CLIENT_ID)
    );

-- ADDING DUMMY VALUES FOR ALL THE TABLES
INSERT INTO CLIENT (FIRSTNAME, LASTNAME, EMAIL, PASSWORD) VALUES ('Jane', 'Doe', 'jane.doe@gmail.com', 'password1');
INSERT INTO CLIENT (FIRSTNAME, LASTNAME, EMAIL, PASSWORD) VALUES ('Bob', 'Smith', 'bob.smith@gmail.com', 'password2');
INSERT INTO CLIENT (FIRSTNAME, LASTNAME, EMAIL, PASSWORD) VALUES ('Alice', 'Johnson', 'alice.johnson@gmail.com', 'password3');
INSERT INTO CLIENT (FIRSTNAME, LASTNAME, EMAIL, PASSWORD) VALUES ('Charlie', 'Brown', 'charlie.brown@gmail.com', 'password4');
INSERT INTO CLIENT (FIRSTNAME, LASTNAME, EMAIL, PASSWORD) VALUES ('David', 'Miller', 'david.miller@gmail.com', 'password5');

-- Insert into ACCOUNTS
INSERT INTO ACCOUNTS (CLIENT_ID, BALANCE) VALUES (1, 1000.00);
INSERT INTO ACCOUNTS (CLIENT_ID, BALANCE) VALUES (2, 2000.00);
INSERT INTO ACCOUNTS (CLIENT_ID, BALANCE) VALUES (3, 3000.00);
INSERT INTO ACCOUNTS (CLIENT_ID, BALANCE) VALUES (4, 4000.00);
INSERT INTO ACCOUNTS (CLIENT_ID, BALANCE) VALUES (5, 5000.00);

-- Insert into BENEFICIARIES
INSERT INTO BENEFICIARIES (CLIENT_ID, BENEFICIARY_FIRSTNAME, BENEFICIARY_LASTNAME) VALUES (1, 'Emily', 'Smith');
INSERT INTO BENEFICIARIES (CLIENT_ID, BENEFICIARY_FIRSTNAME, BENEFICIARY_LASTNAME) VALUES (2, 'Michael', 'Johnson');
INSERT INTO BENEFICIARIES (CLIENT_ID, BENEFICIARY_FIRSTNAME, BENEFICIARY_LASTNAME) VALUES (3, 'Sarah', 'Williams');
INSERT INTO BENEFICIARIES (CLIENT_ID, BENEFICIARY_FIRSTNAME, BENEFICIARY_LASTNAME) VALUES (4, 'James', 'Brown');
INSERT INTO BENEFICIARIES (CLIENT_ID, BENEFICIARY_FIRSTNAME, BENEFICIARY_LASTNAME) VALUES (5, 'Jessica', 'Jones');

-- Insert into TRANSACTIONS
INSERT INTO TRANSACTIONS (SENDER_ID, BENEFICIARY_ID, AMOUNT, DESCRIPTION, DATE, STATUS) VALUES (1, 2, 100.00, 'Payment for services', '2023-01-01 11:00:00', 1);
INSERT INTO TRANSACTIONS (SENDER_ID, BENEFICIARY_ID, AMOUNT, DESCRIPTION, DATE, STATUS) VALUES (2, 3, 200.00, 'Rent', '2023-01-02 11:00:00', 1);
INSERT INTO TRANSACTIONS (SENDER_ID, BENEFICIARY_ID, AMOUNT, DESCRIPTION, DATE, STATUS) VALUES (3, 4, 300.00, 'Casino', '2023-01-03 11:00:00', 1);
INSERT INTO TRANSACTIONS (SENDER_ID, BENEFICIARY_ID, AMOUNT, DESCRIPTION, DATE, STATUS) VALUES (4, 5, 400.00, 'McDonalds', '2023-01-04 09:00:00', 1);
INSERT INTO TRANSACTIONS (SENDER_ID, BENEFICIARY_ID, AMOUNT, DESCRIPTION, DATE, STATUS) VALUES (5, 1, 500.00, 'Train tickets', '2023-01-05 14:00:00', 1);

COMMIT;

-- replica for testing ?